# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.1.13"
    - name: Install dependencies
      run: |
        poetry install
    - name: Activate virtual env
      run: |
        poetry shell
    - name: Run tests
      run: |
        python -m unittest -v -c
